apps/book_reviews/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register$', views.register, name='register'),
	url(r'^login$', views.login, name='login'),
	url(r'^books$', views.home, name='home'),
	url(r'^books/add$', views.add, name='add'),
	url(r'^books/process$', views.process, name='process'),
	url(r'^books/(?P<id>\d+)$', views.show_book, name='show_book'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^users/(?P<id>\d+)$', views.show_user, name='show_user'),
	url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
]

belt_reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.book_reviews.urls', namespace='book_reviews')),
]

apps/book_reviews/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re 
from django.db.models import Count

EMAIL_REGEX = re.compile(r'^[\w\.+_-]+@[\w\._-]+\.[\w]*$')

class UserManager(models.Manager):
	def validate_new(self, **kwargs):
		errors = []

		if len(kwargs['name']) < 2:
			errors.append('Name must be longer than 2 characters.')
		if not EMAIL_REGEX.match(kwargs['email']): 
			errors.append('Not a valid email.')
		email_exists = User.objects.filter(email=kwargs['email'])
		if email_exists:
			errors.append('Email already registered.')
		if len(kwargs['password']) < 8:
			errors.append('Password must be at least 8 characters long.')
		if kwargs['password'] != kwargs['confirm_password']:
			errors.append('Passwords do not match.')

		if errors: 
			return (False, errors)
		else: 
			input_pw = kwargs['password'].encode()
			hashed_pw = bcrypt.hashpw(input_pw, bcrypt.gensalt())
			User.objects.create(name=kwargs['name'], alias=kwargs['alias'], email=kwargs['email'], password=hashed_pw)
			user = User.objects.get(name=kwargs['name'], alias=kwargs['alias'], email=kwargs['email'], password=hashed_pw)
			return (True, user.id)
	def validate_login(self, **kwargs):
		errors = []
		try:
			user = User.objects.get(email__iexact=kwargs['email'])
			return (True, user.id)
		except:
			errors.append('Invalid Email/Password')
			return (False, errors)
			
	def profile_info(self, **kwargs):
		user = User.objects.get(id=kwargs['id'])
		reviews = Review.objects.filter(user=user)
		total_reviews = len(reviews)
		return (user, reviews, total_reviews)

class BookManager(models.Manager):
	def add_book_review(self, **kwargs):
		if kwargs['author'] == '':
			author_name = kwargs['preset_author']
		else:
			author_name = kwargs['author']

		try: 
			author = Author.objects.get(name=author_name)
		except:
			author = Author.objects.create(name=author_name)
		try: 
			book = Book.objects.get(title=kwargs['title'])
		except: 
			book = Book.objects.create(title=kwargs['title'], author=author)

		user = User.objects.get(id=kwargs['user_id'])
		Review.objects.create(description=kwargs['review'], book=book, user=user, stars=kwargs['stars'])
		return book.id

class ReviewManager(models.Manager):
	def destroy_review(self, **kwargs):
		Review.objects.get(id=kwargs['review_id']).delete()

class User(models.Model):
	name = models.CharField(max_length=255)
	alias = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

class Author(models.Model):
	name = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
	title = models.CharField(max_length=255)
	author = models.ForeignKey(Author)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = BookManager()

class Review(models.Model):
	description = models.TextField(max_length=1000)
	book = models.ForeignKey(Book)
	user = models.ForeignKey(User)
	stars = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = ReviewManager()

apps/book_reviews/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User, UserManager, Author, Book, BookManager, Review
from django.contrib import messages

# Create your views here.
def index(request):
	# Author.objects.all().delete()
	# Book.objects.all().delete()
	# Review.objects.all().delete()
	return render(request, 'book_reviews/index.html')

def home(request):
	if 'user_id' in request.session:
		user = User.objects.get(id=request.session['user_id'])
		books = Book.objects.all()
		recent_reviews = Review.objects.all().order_by('-id')[:3]
		context = {
			'name': user.name.title(),
			'alias': user.alias,
			'emai': user.email,
			'books': books,
			'recent_reviews': recent_reviews,
		}
		return render(request, 'book_reviews/home.html', context)
	return redirect(reverse('book_reviews/index'))

def register(request):
	if request.method == 'POST':
		result = User.objects.validate_new(name=request.POST['name'], alias=request.POST['alias'], email=request.POST['email'], password=request.POST['password'], confirm_password=request.POST['confirm_password'])
		if result[0]:
			request.session['user_id'] = result[1]
			return redirect(reverse('book_reviews:home'))
		else:
			for error in result[1]:
				messages.error(request, error)
			return redirect(reverse('book_reviews:index'))

def login(request):
	if request.method == 'POST':
		result = User.objects.validate_login(email=request.POST['email'], password=request.POST['password'])
		if result[0]:
			request.session['user_id'] = result[1]
			return redirect(reverse('book_reviews:home'))
		else: 
			for error in result[1]:
				messages.error(request, error)
			return redirect(reverse('book_reviews:index'))

def logout(request):
	request.session.pop('user_id')
	return redirect(reverse('book_reviews:index'))

def add(request):
	return render(request, 'book_reviews/add.html')

def process(request):
	book_id = new_book_and_review = Book.objects.add_book_review(user_id=request.session['user_id'], title=request.POST['title'], author=request.POST['author'], preset_author=request.POST['preset_author'], stars=request.POST['stars'], review=request.POST['review'])
	return redirect(reverse('book_reviews:show_book', kwargs={'id': book_id}))

def show_book(request, id):
	book = Book.objects.get(id=id)
	author = book.author
	reviews = Review.objects.filter(book=book)
	context = {
		'book': book,
		'reviews': reviews,
	}
	return render(request,'book_reviews/show.html', context)

def show_user(request, id):
	info = User.objects.profile_info(id=id)
	context = {
		'user': info[0],
		'reviews': info[1],
		'total_reviews': info[2],
	}
	return render(request, 'book_reviews/profile.html', context)

def destroy(request, id):
	# Review.objects.get(id=id).delete()
	Review.objects.destroy_review(review_id=id, book_id=request.POST['book_id'])
	return redirect(reverse('book_reviews:show_book', kwargs={'id': request.POST['book_id']}))

apps/book_reviews/templates/book_reviews/add.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='This is probably the biggest project I will do before the exam'> 
	<title>Welcome</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "book_reviews/styles/style.css" %}'>
</head>
<body>
	<div class='container add'>
		<div>
			<h1 class='inline'>Add a New Book Title and a Review</h1>
			<form class='inline' action='{% url "book_reviews:logout" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Logout'>
			</form>
			<form class='inline' action='{% url "book_reviews:home" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Home'>
			</form>
		</div>
		<div>
			<form action='{% url "book_reviews:process" %}' method='POST'>
				{% csrf_token %}
				<label>Book Title: <input type='text' name='title'></label>
				<label>Author:</label>
				<label>Choose from the list:
					<select class='author' name='preset_author'>
						<option>Patrick Rothfuss</option>
						<option>Brandon Sanderson</option>
						<option>David Wong</option>
						<option>Issac Asimov</option>
					</select>
				</label>
				<label>Or add a new author: <input type='text' name='author'></label>
				<label>Review:</label>
				<textarea name='review'></textarea>
				<label>Rating:
					<select name='stars'>
						<option>5</option>
						<option>4</option>
						<option>3</option>
						<option>2</option>
						<option>1</option>
					</select>
				</label>
				<input class='submit btn btn-default' type='submit' value='Add Book and Review'>
			</form>
		</div>
	</div>
</body>
</html>

apps/book_reviews/templates/book_reviews/home.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='This is probably the biggest project I will do before the exam'> 
	<title>Welcome</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "book_reviews/styles/style.css" %}'>
</head>
<body>
	<div class='container home'>
		<div>
			<h1 class='inline'>Welcome, {{name}}!</h1>
			<form class='inline' action='{% url "book_reviews:logout" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Logout'>
			</form>
			<form class='inline' action='{% url "book_reviews:add" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Add Book and Review'>
			</form>
		</div>
		<div class='inline'>
			<h2>Other Books with Reviews:</h2>
			<div class='scroll'>
				{% for book in books %}
					<a href='books/{{book.id}}'>{{book.title}}</a>
				{% endfor %}
			</div>
		</div>
		<div class='inline'>
			<h2>Recent Book Reviews</h2>
			{% for review in recent_reviews %}
			<div class='review'>
				<h3><a href='/books/{{review.book.id}}'>{{review.book.title}}</a></h3>
				<p>Rating: <img src='{% static "book_reviews/images/"%}{{review.stars}}.png'></p>
				<img src=''><img src=''>
				<p class='review'><a href='/users/{{review.user.id}}'>{{review.user.name}}</a>: {{review.description}}</p>
				<p>Posted on: {{review.created_at}}</p>
			</div>
			{% endfor %}
		</div>
	</div>
</body>
</html>

apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='This is probably the biggest project I will do before the exam'> 
	<title>Welcome</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "book_reviews/styles/style.css" %}'>
</head>
<body>
	<div class='container'>
		<h1>Welcome</h1>
		<div class='messages'>
			{% for message in messages %}
				<p {% if message.tags %} class='{{message.tags}}' {% endif %}>{{message}}</p>
			{% endfor %}
		</div>
		<div class='inline'>
			<h3>Register</h3>
			<form class='register' action='{% url "book_reviews:register" %}' method='POST'>
				{% csrf_token %}
				<label>Name</label>
				<input type='text' name='name'>
				<label>Alias</label>
				<input type='text' name='alias'>
				<label>Email</label>
				<input type='text' name='email'>
				<label>Password</label>
				<input type='password' name='password'>
				<p>*Password must be at least 8 characters</p>
				<label>Confirm Password</label>
				<input type='password' name='confirm_password'>
				<input class='submit btn btn-default' type='submit' value='Register'>
			</form>
		</div>
		<div class='inline'>
			<h3>Login</h3>
			<form class='login' action='{% url "book_reviews:login" %}' method='POST'>
				{% csrf_token %}
				<label>Email</label>
				<input type='text' name='email'>
				<label>Password</label>
				<input type='password' name='password'>
				<input class='submit btn btn-default' type='submit' value='Login'>
			</form>
		</div>
	</div>
</body>
</html>

apps/book_reviews/templates/book_reviews/profile.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='This is probably the biggest project I will do before the exam'> 
	<title>Welcome</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "book_reviews/styles/style.css" %}'>
</head>
<body>
	<div class='container profile'>
		<div>
			<form class='inline' action='{% url "book_reviews:logout" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Logout'>
			</form>
			<form class='inline' action='{% url "book_reviews:add" %}' method='POST'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Add Book and Review'>
			</form>
			<form class='inline' action='{% url "book_reviews:home" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Home'>
			</form>			
		</div>

		<h3>Alias: {{user.alias}}</h3>
		<p>Name: {{user.name}}</p>
		<p>Email: {{user.email}}</p>
		<p>Total Reviews: {{total_reviews}}</p>

		<h3 class='other_reviews'>Posted Reviews on the following books</h3>
		{% for book in reviews %}
			<p class='titles'><a href='/books/{{book.book.id}}'>{{book.book.title}}</a></p>
		{% endfor %}
	</div>
</body>
</html>

apps/book_reviews/templates/book_reviews/show.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<meta name='content' description='This is probably the biggest project I will do before the exam'> 
	<title>Welcome</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
	{% load staticfiles %}
	<link rel='stylesheet' type='text/css' href='{% static "book_reviews/styles/style.css" %}'>
</head>
<body>
	<div class='container show'>
		<div>
			<h1 class='inline'>{{book.title}}</h1>
			<h4 class='inline'>by {{book.author.name}}</h4>
			<form class='inline' action='{% url "book_reviews:logout" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Logout'>
			</form>
			<form class='inline' action='{% url "book_reviews:home" %}' method='GET'>
			{% csrf_token %}
				<input class='btn btn-default' type='submit' value='Home'>
			</form>			
		</div>
		<div class='inline'>
			<h3><b>Reviews:</b></h3>
			{% for review in reviews %}
				<hr>
				<p>Rating: <img src='{% static "book_reviews/images/"%}{{review.stars}}.png'></p>
				<p class='review'><a href='/users/{{review.user.id}}'>
				{{review.user.name}}</a>: says: {{review.description}}</p>
				<p class='review'>Posted on {{review.created_at}}</p>
					{% if request.session.user_id == review.user.id %}
						<form action='{% url "book_reviews:destroy" review.id %}' method='POST'>
							{% csrf_token %}
							<input type='hidden' name='book_id' value='{{book.id}}'>
							<input class='btn btn-default' type='submit' value='Delete This Review'>
						</form>
					{% endif %}
			{% endfor %}
		</div>
		<div class='inline review'>
			<form action='{% url "book_reviews:process" %}' method='POST'>
				{% csrf_token %}
				<label>Add a Review: </label>
				<textarea class='review' name='review'></textarea>
				<input type='hidden' name='title' value='{{book.title}}'>
				<input type='hidden' name='author' value=''>
				<input type='hidden' name='preset_author' value='{{book.author.name}}'>
				<label>Rating: 
					<select name='stars'>
						<option>5</option>
						<option>4</option>
						<option>3</option>
						<option>2</option>
						<option>1</option>
					</select> stars.
				</label>
				<input class='btn btn-default' type='submit' value='Submit Review'>
			</form>
		</div>
	</div>
</body>
</html>